from pandas import DataFrame


def descargarData() -> None:
    """
    Descarga el archivo taylor_swift_spotify.json de Google Drive y crea el directorio 'data/' si no existe.

    ## Parametros
    None

    ## Retorna
    Un archivo .json alojado en el directorio "data/"
    """
    ...

def null_review(df: DataFrame) -> DataFrame:
    """
    Esta función realiza un reporte de los datos nulos, tipos y columnas duplicadas de un dataframe.

    ## Parametros
    - df: El dataframe del cual se quiere realizar el reporte

    ## Retorna
    - DataFrame: Un dataframe con el reporte de nulos, filas duplicadas y columnas nulas
    """
    ...

def saveGraph(graph_id: str, tight_layout: bool=True, graph_extension: str='png', resolution: int=300) -> None:
    """
    Downloads a graph generated by matplotlib with the specified name, graph extension and resolution.

    ## Parameters
    - graph_id: Graph name
    - tight_layout: Activate the tigh_layout configuration
    - graph_extension: Extension to save the image (png, jpg, svg, etc...)
    - Resolution: DPI resolution for saving the figure

    ## Returns
    A graph image from matplotlib saved in a 'images' directory
    """
    ...

def multiHist(filename: str, df: DataFrame, bins: int=50, kde: bool=True, bar_color: str='#329D9C', kde_color: str='#472F7D') -> None:
    """
    This function creates a figure containing multiple histograms based on the numeric columns of a given DataFrame.
    
    ## Parameters
    - filename: The file name for the .png graph
    - df: A DataFrame containing at least 1 numeric column (can contain numeric and no-numeric columns)
    - bins: The number of bins to plot in the histograms
    - kde: Flag to plot the kde line in histograms
    - bar_color: Color string or HexCode for the bars
    - kde_color: Color string or HexCode for the kde line

    ## Returns
    A .png image containing the histograms saved in a 'images' directory
    """
    ...